### ISSUE TITLE
The link to the paper is broken

### ISSUE THREAD

**Issue by wehddn** [anaezquerro/recsys-smpd#1]

**Comment by wehddn** [comment]
The link in this sentence is broken : You can find a detailed description of each model in the [paper](https://github.com/anaezquerro/recsys-smpd/blob/main/recsys-spmd.pdf) attached to this repository.

**Comment by anaezquerro** [comment]
oops a typo error in the internal reference hehe :sweat_smile: i've already updated it, thanks!
